### PR TITLE
Panic Safety and Mild Cleanup

### LINKED ISSUE #11: Removing Panics On Failed Parse
Hey kvark, I swear you're everywhere 😄 

I am looking at using this library to convert from OBJ to another silly model format, and I need to deal with invalid inputs because users are handing me this directly. It seems like everything in the library returns results with the exception of the unexpected token branches of the mtl and the obj parser. 

Would you be open to a patch that turns those panics into a Err? There are a couple ways I could try to do this depending how much you care about backwards compatibility. Some ideas off the top of my head:
 - Add a new method `load_err`/`load_buf_err`, have it be the main implementation, and have the current method call it's error friend then call unwrap.
 - Modify the current methods to return `Result<Obj, ObjError>` where ObjError is an enum containing IO Error/Parsing Error, possibly with an internal parsing error kind enum.

Let me know if you've had any thoughts about this in the past and what requirements you would want for something like this.

### PR DESCRIPTION
**Pull request by cwfitzgerald**
Resolves #11.

This PR removes all instances of panics where the user didn't ask for a panic. I've tested the tests and against my codebase using it, and everything seems still in order.

Notable changes
 - Added `ObjError`, `MtlError`, and `MtlMissingType`
 - Refactored `Obj::{parse_vertex, parse_texture, parse_normal}` to return their output instead of modifying state. Combined them into `parse_two` and `parse_three` to reduce duplicate code.
 - Added hack to allow filenames with spaces as the mtllib/texture names. (Explanation in comment)
 - Added private function `Obj::load_single_mtl` to make error handling more concise and remove duplicate code.

Breaking Changes:
 - Everything now returns a `ObjError` or `MtlError` instead of a `io::Error`
 - Neither `ObjError` nor `MtlError` implement `Display`. Should they?

Now that I've dug a bit into the codebase, there are a couple of improvements I still want to make. Feel free to comment on any of them 😄. Vaguely in order of importance:
 - Run rustfmt on the codebase & verify rustfmt in CI
 - Create function `Obj::load_mtl_fn` that takes a function which takes the base directory and the mtllib name and returns _something_ that `impl Read`. This will allow special file lookup or file loading if need be. `Obj::load_mtl` will just call `Obj::load_mtl_fn` with a function that uses how it currently resolves now. Will file an issue about this tmmr.
 - Document all the things.
 - Maybe implement #2.

### CODE REVIEW

File: src/mtl.rs [hunk 1]
```diff
@@ -69,6 +70,37 @@ impl Material {
     }
 }
 
+/// Indicates type of a missing value
+#[derive(Debug)]
+pub enum MtlMissingType {
+    /// i32
+    Tyi32,
```
Comment (kvark) [inline src/mtl.rs]: Why Do we need `Ty` prefix?

File: src/mtl.rs [hunk 2]
```diff
@@ -69,6 +70,37 @@ impl Material {
...
+    /// f32
+    Tyf32,
+    /// String
+    TyString,
+}
+
+/// Errors parsing or loading a .mtl file.
+#[derive(Debug)]
+pub enum MtlError {
+    IoError(io::Error),
```
Comment (kvark) [inline src/mtl.rs]: Could we just have `Io` instead of `IoError`?

File: src/mtl.rs [hunk 3]
```diff
@@ -79,50 +111,52 @@ impl<'a> From<Material> for Cow<'a, Material> {
 struct Parser<I>(I);
 
 impl<'a, I: Iterator<Item = &'a str>> Parser<I> {
-    fn get_vec(&mut self) -> Option<[f32; 3]> {
+    fn get_vec(mut self) -> Result<[f32; 3], MtlError> {
```
Comment (kvark) [inline src/mtl.rs]: why are all the function signatures changed to accept `self` by value?

File: src/obj.rs [hunk 4]
```diff
@@ -19,44 +19,82 @@ pub use genmesh::{Polygon, Quad, Triangle};
...
-            n => return Err(format!("Unsupported: polygon with {} verts", n)),
+            n => return Err(ObjError::GenMeshTooManyVertsInPolygon {line_number, vert_count}),
         }
     }
 }
 
+/// Errors parsing or loading a .obj file.
+#[derive(Debug)]
+pub enum ObjError {
+    IoError(io::Error),
```
Comment (kvark) [inline src/obj.rs]: similarly, here, could be `Io`

File: src/obj.rs [hunk 5]
```diff
@@ -19,44 +19,82 @@ pub use genmesh::{Polygon, Quad, Triangle};
...
+    /// `mtllib` command issued, but no name was specified.
+    MissingMTLName {
+        line_number: usize,
+    },
+    /// [`genmesh::Polygon`] only supports triangles and squares.
+    #[cfg(feature = "genmesh")]
+    GenMeshTooManyVertsInPolygon{
+        line_number: usize,
+        vert_count: usize,
+    }
```
Comment (kvark) [inline src/obj.rs]: nit: missing trailing comma?

**Review by kvark — CHANGES_REQUESTED** [review]
Looks wonderful, just a few minor concerns here!

File: src/mtl.rs (hunk 1 above)
Comment (cwfitzgerald) [reply src/mtl.rs]: We don't. This was caused by two issues on my end.

 - I forgot that enums generally have their variants PascalCase.
 - I thought that `i32` would be an invalid variant. It isn't, but it doesn't matter because point 1 :)

File: src/mtl.rs (hunk 3 above)
Comment (cwfitzgerald) [reply src/mtl.rs]: Good catch. This change stemmed from my use of fold inside `get_string` as fold takes the iterator (`self.0`) by value which caused issues. I think this behavior is reasonable for get_string as it consumes the rest of the line (and the iterator). I have changed the rest back to `&mut self` however as they don't consume the whole line.

**Comment by cwfitzgerald** [comment]
All changes should be addressed :)

File: src/mtl.rs [hunk 6]
```diff
@@ -79,50 +111,52 @@ impl<'a> From<Material> for Cow<'a, Material> {
...
         }
     }
 
-    fn get_string(&mut self) -> Option<String> {
+    fn get_string(mut self) -> Result<String, MtlError> {
         match self.0.next() {
-            Some(v) => Some(v.to_string()),
+            Some(v) => {
+                // See note on mtllib parsing in obj.rs for why this is needed/works
+                Ok(self.0.fold(v.to_string(), |mut existing, next| {
```
Comment (kvark) [inline src/mtl.rs:152]: is that basically a `join`?

File: src/mtl.rs [hunk 7]
```diff
@@ -79,50 +111,52 @@ impl<'a> From<Material> for Cow<'a, Material> {
...
             None => {
-                println!("missing f32");
-                None
+                Err(MtlError::MissingValue(MtlMissingType::F32))
             }
         }
     }
 
-    fn get_string(&mut self) -> Option<String> {
+    fn get_string(mut self) -> Result<String, MtlError> {
```
Comment (kvark) [inline src/mtl.rs]: hmm, this is still inconsistent with the other methods.
If you need it to have `self` by value, need to rename it to `into_string`

**Review by kvark — CHANGES_REQUESTED** [review]

File: src/mtl.rs (hunk 6 above)
Comment (cwfitzgerald) [reply src/mtl.rs:152]: I think join is part of itertools

File: src/mtl.rs (hunk 7 above)
Comment (cwfitzgerald) [reply src/mtl.rs]: Fixed.

**Review by kvark — APPROVED** [review]
Cool, thanks!
bors r+

**Comment by kvark** [comment]
Are the commits buildable independently? Otherwise we'll squash it (no bors here)

**Comment by cwfitzgerald** [comment]
I think they all build. I don't recall running tests on all of them but I only committed once I got things working.
